[project]
name = "defidune"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.3.0",
    "goat-sdk-plugin-rugcheck (==0.1.1)",
    "goat-sdk-plugin-allora (>=0.1.1,<0.2.0)",
]
